name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build-and-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake g++ libgtest-dev google-mock

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Test
        run: |
          cd build
          ./test_bitmap
